### ISSUE TITLE
Add support for free-form array with named schema in `additionalProperties`

### ISSUE THREAD

**Issue by jtreminio** [jtreminio/oseg#30]
Given

```yaml
components:
  schemas:
    FlagInput:
      type: object
      required:
      - ruleId
      - flagConfigVersion
      properties:
        ruleId:
          type: string
          description: The ID of the variation or rollout of the flag to use. Use
            "fallthrough" for the default targeting behavior when the flag is on.
          example: e432f62b-55f6-49dd-a02f-eb24acf39d05
        flagConfigVersion:
          type: integer
          description: The flag version
          example: 12
        notInExperimentVariationId:
          type: string
          description: The ID of the variation to route traffic not part of the experiment
            analysis to. Defaults to variation ID of baseline treatment, if set.
          example: e432f62b-55f6-49dd-a02f-eb24acf39d05
    FlagsInput:
      type: object
      additionalProperties:
        "$ref": "#/components/schemas/FlagInput"
```

in csharp the property `FlagInput` is defined as `Dictionary<string, FlagInput>`.

Free-form (key:value) objects can include named objects
