### ISSUE TITLE
enum in API call method should be literal string value

### ISSUE THREAD

**Issue by jtreminio** [jtreminio/oseg#31]
Given

```yaml
    post:
      description: Create a new AI config within the given project.
      operationId: postAIConfig
      parameters:
      - description: Version of the endpoint.
        explode: false
        in: header
        name: LD-API-Version
        required: true
        schema:
          enum:
          - beta
          type: string
        style: simple
```

the `LD-API-Version` property to be listed in API call method, should use literal string value `beta` (or whatever is defined in `enum` array) instead of a constant.
