### ISSUE TITLE
PHP - Enum names must respect reserved keywords

### ISSUE THREAD

**Issue by jtreminio** [jtreminio/oseg#37]
On

```yaml
query_operator:
  type: string
  description: query operator name
  enum:
    - AND
    - OR
```

the generated names would be:

```php
public const QUERY_OPERATOR__AND = 'AND';
public const QUERY_OPERATOR__OR = 'OR';
```
